[[main]]
  name = "首页"
  url = "/"
  weight = 1

[[main]]
  name = "归档"
  url = "/archives/"
  weight = 2

[[main]]
  name = "分类"
  url = "/categories/"
  weight = 3

[[main]]
  name = "关于"
  url = "/about/"
  weight = 4
